### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by mb849482677** [rakibhstu/Chat-Example-Laravel-VueJs-Websocket-#1]
Exception `BeyondCode\LaravelWebSockets\WebSockets\Exceptions\UnknownAppKey` thrown: `Could not find app key `anyKey`.`
Unknown app id: exception `BeyondCode\LaravelWebSockets\WebSockets\Exceptions\UnknownAppKey` thrown: `Could not find app key `anyKey`.`.
Connection id  sending message {"event":"pusher:error","data":{"message":"Could not find app key `anyKey`.","code":4001}}
Connection id  closed.
Exception `ErrorException` thrown: `Undefined property: Ratchet\Server\IoConnection::$app`

**Comment by rakibdevs** [comment]
I am really sorry about that. I have to share  .env configuration info.

Please set this configuration in .env
```
PUSHER_APP_ID= anyId
PUSHER_APP_KEY= anyKey
PUSHER_APP_SECRET= anySecret
```

and BROADCAST_DRIVER as pusher
`BROADCAST_DRIVER=pusher`

and don't forget to run `php artisan config:clear ` to clear config cache.
